# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 04:24
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, validators=[blog.models.min_length_3_validator]),
        ),
    ]
